# Docker image
# Build a Docker image to run, deploy, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  dockerId: davidxchen
  imageName: cartrackerapi

steps:
- script: |
    docker build -t $(dockerId)/$(imageName) -f Dockerfile.production
    docker login -u $(dockerId) -p $(pswd)
    docker push $(dockerId)/$(imageName):latest
    docker push $(dockerId)/$(imageName):$(build.buildId)
  env:
    pswd: $(dockerPassword)  